fast-af/fast-checkout-woocommerce

- includes/fast-plugin-settings.php
Ran into an issue where the Test Mode checkbox on the Fast settings page could not be checked or unchecked. This update removes the dependency on checking for a falsey value, and just checks for a specific default value.
Install the plugin and verify that you can enable and disable test mode via the Fast settings page.
> Update test mode to make not set more specific

- includes/fast-plugin-settings.php
Some sellers were complaining about the Fast plugin changing the fonts in the WordPress admin. This update makes the Fast admin styles more targeted to just the `<div>` that wraps the Fast settings. It adds a class of `fast-settings` to the wrapper `<div>` and then updates the selectors in the CSS to include the `.fast-settings` class.
This code is up on the Fast dev site: https://fasttestdev.wpcomstaging.com/
1. Open the Fast [settings page in the WP admin](https://fasttestdev.wpcomstaging.com/wp-admin/admin.php?page=fast).
2. Verify that the WP admin bar and sidebar nav elements do not have "Lucida Grande" as their font family.
3. Verify that the Fast settings form does use "Lucida Grande" as its font family.
> Make Fast admin styles more targeted

- README.md
Merging documentation updates from Friday, March 26 pre-9am CT.
> Documentation update from 3/26 AM

- README.md
> fix broken install guide toc links

- includes/routes/shipping.php
Current validation assumes that if multiple packages we also have multiple addresses. I switched the validation for cases with multiple packages to ensure they are the same before proceeding.
Call the shipping endpoint for a specific item with promotion packages and if the addresses are the same the response should contain available shipping options.
> Shipping Options endpoint single address validation fix

- includes/routes/shipping.php
We have seen that some older items may apeear in the cart init phase and merging those with new items may result in unwanted shipping options / option prices. This PR clears the cart before the items in the requests are added into it.
This behavior was 100% reproducable from the backend whereas using postman we were not able to reproduce so I suspect it might be related to session being persisted somehow.
> Shipping Options endpoint clear cart before filling

- readme.txt
Update the latest version of WordPress with which this plugin has been tested to 5.7, since this plugin is regularly tested with WordPress 5.7.
Nothing to test. This is just an update to the `readme.txt` file.
> Update WP tested version to 5.7

- includes/checkout.php
Hides the Fast Checkout button for PDP/Cart for "Variable Subscription" products.
Fast Checkout doesn't yet support subscriptions, but we missed checking for this product type, which [is part of the official WooCommerce Subscriptions plugin](https://github.com/wp-premium/woocommerce-subscriptions/blob/master/includes/class-wc-product-variable-subscription.php#L17).
Repro instructions in PINT-85.
> Hide Fast button for variable subscription products

- fast.php
- readme.txt
Bump the version number to 1.0.1 and update the changelog to include the changes.
No testing needed. Just updating the version number.
> Bump the version to 1.0.1 and update changelog

- includes/shortcodes.php
This replaces `wp_shortcode_atts` with `shortcode_atts` because `wp_shortcode_atts` does not exist.
Verify that there are no errors on this page: https://fasttestdev.wpcomstaging.com/fast-shortcodes/
@brikr @ilkerulutas this is ready for review.
> PINT-387 Fix incorrect function name

- fast.php
- readme.txt
Bump the version number to 1.0.3 and update the changelog.
No testing needed since no code is changed.
> Bump version to 1.0.3 and update changelog

- fast.php
- includes/admin/constants.php
- includes/admin/settings.php
- includes/checkout.php
- includes/debug.php
- includes/hide.php
- includes/login.php
- includes/routes.php
- includes/shortcodes.php
- includes/utilities.php
Add a debug mode that enables logging messages to a `fastwc-` log file using the WooCommerce logging mechanism.
1. Login to the [dev site admin](https://fasttestdev.wpcomstaging.com/wp-admin/).
2. Go to the [Fast settings page](https://fasttestdev.wpcomstaging.com/wp-admin/admin.php?page=fast).
3. Enable Debug Mode by checking the checkbox next to the debug mode setting.
4. Perform some tasks on the front end.
5. Go back to the admin and look at the [logs in WooCommerce](https://fasttestdev.wpcomstaging.com/wp-admin/admin.php?page=wc-status&tab=logs).
6. Verify that a `fastwc-` log exists and verify that logging occurred.
7. Go back to the Fast settings page and disable debug mode.
@ilkerulutas this is ready for a review.
> PINT-403 Add debug mode

- fast.php
- readme.txt
Bump the plugin version number to 1.04.
No testing required.
> Bump the plugin version to 1.0.4

- includes/routes.php
This fixes a syntax error in the logging call in the API permissions check.
> Fix syntax error

- fast.php
- readme.txt
Bump the version number to 1.0.5 and update the changelog.
> Bump the version to 1.0.5

- fast.php
- readme.txt
Update the version number to 1.0.6 and add a changelog.
> Update version to 1.0.6 and add changelog

- includes/admin/settings.php
Update the Fast settings page to display in tabs rather than as a long list of settings.
1. Log in to the [staging admin](https://fasttestdev.wpcomstaging.com/wp-admin/).
2. Go to the [Fast settings page](https://fasttestdev.wpcomstaging.com/wp-admin/admin.php?page=fast).
3. Verify that the settings are divided up into tabs.
4. Verify that you can still save the settings as before.
5. Verify that the settings still have the same effect as they did before.
@ilkerulutas @brikr this is ready for review.
> PINT-421 Add tabs to the settings page

- fast.php
- readme.txt
Bump the plugin version to 1.0.7 and add a changelog.
> Bump the version to 1.0.7 and add a changelog

- fast.php
- includes/admin/settings.php
- includes/debug.php
- includes/version.php
Moves the WooCommerce check to the Fast plugin entry point, and makes loading Fast plugin files contingent on the existence of an active WooCommerce installation.
1. Disable WooCommerce and verify that an admin alert message is displayed that says "Your Fast plugin won't work without an active WooCommerce installation."
> PINT-429 Check for WooCommerce before loading any files

- fast.php
- readme.txt
- templates/admin/tabs/fast-support.php
Update the plugin version number to 1.0.8 and add a changelog. Update the "Submit Ticket" link to say "Get Help" and link to https://help.fast.co/hc/en-us.
> Update the plugin to version 1.0.8

- includes/admin/notices.php
- includes/admin/settings.php
Display a notice in the WordPress admin when the Fast plugin is in Test Mode or Debug Mode. This will help the seller and the Fast CS/TCS team know more easily whether or not the plugin is in Test Mode or Debug Mode.
1. Login to the [staging admin](https://fasttestdev.wpcomstaging.com/wp-admin/).
2. Visit the [Fast settings page Test Mode tab](https://fasttestdev.wpcomstaging.com/wp-admin/admin.php?page=fast&tab=fast_test_mode).
3. Enable Test Mode.
4. Verify that a notice appears in the admin that says "Fast Checkout for WooCommerce is currently in Test Mode."
5. Enable Debug Mode.
6. Verify that a notice appears in the admin that says "Fast Checkout for WooCommerce is currently in Debug Mode."
@ilkerulutas @brikr this is now ready for review.
> PINT-478 - Add test mode and debug mode admin notices

- fast.php
- includes/assets.php
- includes/hide.php
- readme.txt
Update the plugin version number to 1.1.0 and add a changelog.
> Update the plugin to version 1.1.0

- includes/admin/constants.php
- includes/admin/settings.php
- includes/assets.php
- includes/utilities.php
- templates/fast-cart.php
- templates/fast-checkout.php
- templates/fast-login.php
- templates/fast-mini-cart.php
- templates/fast-pdp.php
Update how the button styles are loaded. This moves the `<style>` tags into the `<head>` of the page rather than inline below the button. Also adds an option in the Styles tab in the Fast settings page that lets you disable styles altogether. That would allow for adding styles from the theme or some other different means.
See https://fastaf.atlassian.net/browse/PINT-527
1. Visit https://fasttestdev.wpcomstaging.com/
2. Verify that the Fast button styles are loaded in the `<head>` of each page rather than just below the button.
3. Login to the [admin](https://fasttestdev.wpcomstaging.com/wp-admin).
4. Visit the [Styles tab of the Fast settings page](https://fasttestdev.wpcomstaging.com/wp-admin/admin.php?page=fast&tab=fast_styles).
5. Uncheck the option for loading the styles.
6. Save the …
> PINT-527 - Update button style loading

- fast.php
- readme.txt
Update the version number to 1.1.1 and update the changelog.
> Update version number to 1.1.1 and update changelog

- includes/version.php
Update the function that checks for an active WooCommerce installation. Use the built-in `is_plugin_active()` function, which accounts for network-active plugins in a [WordPress Multisite](https://wordpress.org/support/article/glossary/#multisite) installation.
See [PINT-560](https://fastaf.atlassian.net/browse/PINT-560) for details.
1. [Set up a WordPress multisite](https://wordpress.org/support/article/create-a-network/)
2. Install WooCommerce
3. Network-activate WooCommerce
4. Install Fast Checkout
5. Activate the Fast plugin on 1 site in the network. Do not network-activate the Fast plugin.
6. Verify that the Fast plugin displays the error message "Your Fast plugin won't work without an active WooCommerce installation."
7. Update the Fast plugin with the code from this branch.
8. …
> PINT-560 - Update function to check for active WooCommerce

- fast.php
- readme.txt
Update version number to 1.1.2 and update change log
N/A
> Update version number to 1.1.2 and update change log

- includes/hide.php
PR #58 was submitted to fix warnings due to some minor issues in the hide functions. After reviewing the PR and the rest of the hide functions, I found a few other minor issues that were worth fixing. This update resolves the issues from #58 as well as those other issues.
1. Visit https://fasttestdev.wpcomstaging.com/
2. Set up products for which the Fast Checkout buttons should be hidden: out of stock product, product selected to be hidden, product with addons, grouped product, subscription product.
3. Verify that the buttons are hidden when they should be.
4. Verify that there are no PHP warnings or errors.
@brikr @ilkerulutas this is ready for review
> [PINT-564] - Fix warnings in hide functions

- fast.php
- readme.txt
Update the version number to 1.1.3 to prepare for the next release.
> Update the version number to 1.1.3

- includes/routes/class-shipping.php
Getting undefined index error on shipping endpoint. See https://app.datadoghq.com/logs?query=trace_id%3A4620605341570033724&cols=core_host%2Ccore_service&event=AQAAAXuoL68kDAVpkQAAAABBWHVvTDdtT0FBREVnWVdfQ2NmRFJRQUM&index=&messageDisplay=inline&stream_sort=desc&from_ts=1630613293948&to_ts=1630615302725&live=false
We need to add validation to this code to make sure that the shipping object is not empty before trying to assign it to the `$customer_props` array.
Verify that the shipping endpoint is working properly in staging.
> PINT-610 - Make sure the shipping object is not empty

- fast.php
- readme.txt
Update version number to 1.1.4 and add changelog
> Update version number to 1.1.4 and add changelog

- includes/admin/notices.php
- includes/webhooks.php
- templates/admin/tabs/fast-status.php
Update the webhook check to make sure that the webhooks are actually installed. The original webhook check assumed that the webhooks were properly installed and only check for disabled webhooks.
1. Login to the [staging server.](https://fasttestdev.wpcomstaging.com/wp-admin)
2. Remove one of the active webhooks.
3. Verify that a notice is displayed showing that a webhook is missing.
@ilkerulutas @brik this is ready for a review.
> PINT-640 - Update webhook check

- includes/webhooks.php
Remove the Fast webhook cache when a webhook is saved in case that changes whether or not any webhooks are missing.
@ilkerulutas @brikr this is ready for a review.
> PINT-640 - Remove webhook cache

- fast.php
- readme.txt
Update the version number to 1.1.5 and add the changelog.
> Bump the version number to 1.1.5 and add changelog

- fast.php
- includes/admin/settings.php
This update adds links to the Fast settings page as well as a link to the Fast website from the Fast plugin listing in the plugins page of the admin.
1. Login to the [staging admin](https://fasttestdev.wpcomstaging.com/wp-admin).
2. Go to the [plugins page](https://fasttestdev.wpcomstaging.com/wp-admin/plugins.php).
3. Verify that the Fast Checkout for WooCommerce plugin listing now includes a link to the Fast website and the Fast settings page in the admin.
@ilkerulutas @brikr this is ready for review.
> PINT-661 - Add settings link to plugins page

- fast.php
- includes/admin/settings.php
After the Fast plugin is activated, this update redirects the admin to the Fast settings page.
1. Login to the [staging admin](https://fasttestdev.wpcomstaging.com/wp-admin/).
2. Go to the [plugins page](https://fasttestdev.wpcomstaging.com/wp-admin/plugins.php).
3. Deactivate the Fast Checkout for WooCommerce plugin, and then activate it again.
4. Verify that you are redirected to the Fast settings page after activating the plugin.
@ilkerulutas @brikr this is ready for review.
> PINT-662 - Redirect after activation

- changelog.txt
- readme.txt
Moves older changelog entries into a changelog.txt file to keep the readme.txt file from getting too large, as recommended here: https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#file-size
N/A
@ilkerulutas @brikr this is ready for review.
> PINT-628 - Add changelog.txt file

- fast.php
- includes/admin/constants.php
- includes/admin/settings.php
- includes/third-party.php
- includes/third-party/class-plugin.php
- includes/third-party/class-woocommerce-tiered-pricing-table.php
- templates/admin/tabs/fast-third-party.php
Add a standard way to add code to mitigate conflicts with third-party plugins.
1. Login to the staging admin.
2. Go to the Plugins page.
3. Deactivate the WooCommerce Tiered Pricing Table plugin.
4. Go to the Fast settings page.
5. Verify that the "Third-Party Plugins" tab is not there.
6. Go back to the Plugins page.
7. Activate the WooCommerce Tiered Pricing Table plugin.
8. Go back to the Fast settings page.
9. Verify that the "Third-Party Plugins" tab is there.
1. Go to the Fast settings page.
2. Click on the "Third-Party Plugins" tab.
3. Make sure that that checkbox is checked by "WooCommerce Tiered Pricing Table"
4. Go to the front end of the site.
5. Click on the Album product.
6. Set the quantity to 10
7. Click the Fast Checkout button
8. Verify that the $5 per item price is …
> Resolves PINT-740 - Add tools mitigate plugin conflicts

- fast.php
- readme.txt
Update the version number to 1.1.9 and update the changelog.
> Bump version to 1.1.9 and update changelog

- includes/assets.php
@seldyyy reported an issue where the Fast admin scripts, specifically the Select2 plugin for jQuery, were interfering with other plugin scripts. This update makes it so that the Fast admin scripts only load on the Fast settings pages.
1. Login to the staging admin.
2. Verify that the Fast scripts are only loaded on the Fast settings pages.
> Enqueue Fast admin scripts only on Fast settings pages

- includes/admin/constants.php
- includes/admin/settings.php
- includes/checkout.php
Add an option to hide the standard WooCommerce checkout buttons in the mini cart widget and on the cart page.
1. Login to staging
2. Go to the Fast settings page and click on the Options tab.
3. Check the option to "Hide WooCommerce Checkout Buttons on Cart"
4. Verify that the standard WooCommerce checkout buttons are not displayed on the mini cart widget or the cart page.
> PINT-799 - Add option to hide the WooCommerce cart checkout buttons

- includes/checkout.php
- includes/routes/class-shipping.php
An issue was discovered where if a coupon was limited to a single use per customer, it does not work if the order is changed via the Fast checkout window because the coupon usage count in WooCommerce was getting incremented more than once. This resulted in an error because the coupon usage limit had been reached for that particular coupon.
This update prevents the coupon from being re-applied to the order if/when it gets submitted multiple times with REST API requests, which prevents the usage count from falsely increasing beyond the usage limit.
1. Login to staging.
2. Create a coupon that is limited to a single use per user.
3. Purchase a product with Fast Checkout.
4. Apply the coupon via the Fast checkout window.
5. Edit the order in the Fast checkout window by changing the quantity. …
> PINT-835 - Only apply coupons if different

- includes/admin/constants.php
- includes/admin/settings.php
- includes/checkout.php
See [PINT-890](https://fastaf.atlassian.net/browse/PINT-890). Update the redirect URL functionality to include a filter to allow site owners to customize the redirect URL for after an order is created.
> PINT-890 - Update order redirect functionality

- includes/checkout.php
- includes/utilities.php
Some hosts don't allow direct access to the `$_GET` variable, so this update uses WordPress' `get_query_var` function instead. Also add `fast_order_id` parameter to URL and include it in the redirect URL filter.
1. Go to https://fasttestdev.wpcomstaging.com/product/album/?fast_order_created=123456&fast_is_pdp=1
2. Verify that it redirects to https://fasttestdev.wpcomstaging.com/cart-checkout-redirect-page/?order_id=123456
> Use get_query_var instead of $_GET

- includes/checkout.php
Fix a PHP notice about undefined variables.
> Fix PHP notice

- includes/checkout.php
Add `exit` function after `wp_safe_redirect` function.
> Exit after redirect

- includes/blocks/class-block.php
- includes/checkout.php
- includes/login.php
- includes/shortcodes.php
- includes/utilities.php
- includes/widgets/class-widget.php
Add hooks to strategic parts of the code to better enable customization by 3rd-party developers.
> PINT-979 - Add hooks

- fast.php
- includes/admin/constants.php
- includes/admin/settings.php
- includes/upgrade.php
- templates/admin/fast-settings-footer.php
Update the onboarding URL to the new seller signup URL.
1. Login to staging.
2. Verify that the new seller signup URL is being used instead of the dashboard (/business) URL.
> PINT-991 - Update seller signup url

- includes/webhooks.php
This update fixes some small issues with the webhook status check.
1. Login to staging.
2. Go to the Fast status tab.
3. Verify that the webhooks status is displaying correctly.
> Update webhooks check
